services:
  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"

  spotlight:
    image: ghcr.io/getsentry/spotlight:latest
    restart: on-failure
    ports:
      - "8969:8969"
