packages:
  - examples/*
  - packages/*

catalog:
  ioredis: ^5.4.2
  pg: ^8.13.1
  "@types/pg": ^8.11.10
  typescript: ^5.9.3
  vitest: ^3.2.4
  vite-tsconfig-paths: ^5.1.4
  "@biomejs/biome": ^2.2.5
  turbo: ^2.5.8
  zod: ^4.1.12
